version: '3'
services: 
    web:
        build: .
        container_name: express
        restart: always
        ports:
            - "4040:4040"
        depends_on: 
            - mongo
    mongo:
        container_name: mydatabase
        image: mongo
        restart: unless-stopped
        ports: 
            - "27017:27017"