version: '3'

services: 
    web:
        container_name: express-node
        restart: always
        build: .
        ports:
            - "6000:3000"
        links: 
            - mongo
    mongo:
        container_name: mydatabase
        image: mongo
        ports: 
            - "27017:27017"





# version: '3'

# services:
#     web:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         image: nodejs
#         command: npm run dev
#         container_name: web-express
#         restart: unless-stopped
#         env_file: .env
#         environment: 
#             - DB_USER=$DB_USER
#             - DB_PASSWORD=$DB_PASSWORD
#             - DB_HOST=$DB_HOST
#             - DB_PORT=$DB_PORT
#             - DB_NAME=$DB_NAME
#         ports: 
#             - "8080:8080"
#         volumes: 
#             - .:/home/node/app
#             - node_modules:/home/node/app/node_modules
#         links: 
#             - "db"
#         networks: 
#             - app-network

#     db:
#         image: mongo:4.1.8-xenial
#         container_name: database-mongo
#         restart: unless-stopped
#         ports: 
#             - "27017:27017"
#         env_file: .env
#         environment: 
#             - MONGO_INITDB_ROOT_USERNAME=$DB_USER
#             - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
#         volumes: 
#             - dbdata:/data/db
#         networks: 
#             - app-network

# networks: 
#     app-network:
#         driver: bridge

# volumes: 
#     dbdata:
#     node_modules: